import { timingSafeEqual } from "node:crypto";
import { getPool } from "../db.js";
import { collectSource } from "../services/collector.js";
import { calculateFreshness } from "../services/freshness.js";
function authorized(request, token) { const supplied = request.headers["x-ops-token"] ?? request.headers.authorization?.replace(/^Bearer\s+/i, ""); if (!token || !supplied) return false; const a=Buffer.from(String(supplied)),b=Buffer.from(token); return a.length===b.length&&timingSafeEqual(a,b); }
const date = (value) => value ? new Date(value).toISOString() : null;
export async function opsRoutes(app, { config, database }) {
  app.addHook("onRequest", async (request, reply) => { if (request.url.startsWith("/v1/ops/") && !authorized(request, config.OPS_API_TOKEN)) return reply.code(401).send({ detail: "Invalid or missing operations token" }); });
  const db = () => database ?? getPool(config);
  app.get("/v1/ops/snapshots", async (request, reply) => { const limit=Math.min(Math.max(Number(request.query.limit)||20,1),100), params=[]; let where=""; if(request.query.source){const [sources]=await db().execute("SELECT id FROM source_registry WHERE name=?",[request.query.source]);if(!sources[0])return reply.code(404).send({detail:"source not found"});where="WHERE source_id=?";params.push(sources[0].id);} params.push(limit); const [rows]=await db().execute(`SELECT id,source_id,fetched_at,http_status,content_hash,object_key,content_length,compressed_length,compression,error,parser_version FROM source_snapshot ${where} ORDER BY fetched_at DESC LIMIT ?`,params); return {snapshots:rows.map(r=>({...r,fetched_at:date(r.fetched_at)}))}; });
  app.get("/v1/ops/observations", async (request) => { const limit=Math.min(Math.max(Number(request.query.limit)||50,1),200), filters=[],params=[]; if(request.query.source){filters.push("sr.name=?");params.push(request.query.source);} if(request.query.metric){filters.push("o.metric=?");params.push(request.query.metric);} if(request.query.station){filters.push("s.source_station_id=?");params.push(request.query.station);} params.push(limit); const [rows]=await db().execute(`SELECT o.id,o.station_id,o.metric,o.value,o.unit,o.observed_at,o.fetched_at,o.quality_state,o.thresholds_json AS thresholds,o.raw_text FROM observation o JOIN station s ON s.id=o.station_id JOIN source_registry sr ON sr.id=s.source_id ${filters.length?`WHERE ${filters.join(" AND ")}`:""} ORDER BY o.observed_at DESC LIMIT ?`,params); return {observations:rows.map(r=>({...r,value:r.value===null?null:String(r.value),observed_at:date(r.observed_at),fetched_at:date(r.fetched_at)}))}; });
  app.get("/v1/ops/health/sources", async () => { const [sources]=await db().execute("SELECT * FROM source_registry ORDER BY name"); const result=[]; for(const source of sources){const [snaps]=await db().execute("SELECT * FROM source_snapshot WHERE source_id=? ORDER BY fetched_at DESC LIMIT 1",[source.id]);const [obs]=await db().execute("SELECT MAX(o.observed_at) observed_at,MAX(o.fetched_at) fetched_at FROM observation o JOIN station s ON s.id=o.station_id WHERE s.source_id=?",[source.id]);result.push({name:source.name,enabled:Boolean(source.enabled),last_snapshot:snaps[0]?{id:snaps[0].id,fetched_at:date(snaps[0].fetched_at),http_status:snaps[0].http_status,content_length:snaps[0].content_length,compressed_length:snaps[0].compressed_length,error:snaps[0].error}:null,last_observed_at:date(obs[0].observed_at),fetched_at:date(obs[0].fetched_at),freshness:calculateFreshness(obs[0].observed_at,obs[0].fetched_at,source.freshness_warning_minutes??45,source.freshness_critical_minutes??90)});} return{sources:result,computed_at:new Date().toISOString(),disclaimer:"Internal freshness view — not a public forecast"}; });
  app.post("/v1/ops/collect", async (request, reply) => { try{return await collectSource(request.query.source??"pdrrmo",config,db());}catch(error){return reply.code(error.statusCode??500).send({detail:error.message});} });
}
